apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.database.password | quote }}

  AWS_ACCESS_KEY_ID: {{ .Values.minio.rootUser | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.minio.rootPassword | quote }}