apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    app: postgres
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  type: ClusterIP