{{- $postgresPort := 5432 -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
spec:
  selector:
    app: postgres
  ports:
    - port: {{ $postgresPort }}
      targetPort: {{ $postgresPort }}
  type: ClusterIP