apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-minio-secret
type: Opaque
stringData:
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | quote }}