apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-minio
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.minio.ports.api }}
      targetPort: {{ .Values.minio.ports.api }}
      protocol: TCP
      name: api
    - port: {{ .Values.minio.ports.console }}
      targetPort: {{ .Values.minio.ports.console }}
      protocol: TCP
      name: console
  selector:
    app: minio